### ISSUE TITLE
bug: incorrect implementation of `.shuffled()` + bad performance

### ISSUE THREAD

**Issue by InSyncWithFoo** [qexat/magic-list#52]
The current implementation is incorrect and has a very bad-looking average time complexity of $O(n^2)$, worst case $O(\infty)$.

https://github.com/qexat/magic-list/blob/535c54f20505767ad65cd2c7fccbb1ea2fb70258/magic_list/prelude.py#L155-L163

```py
l = L[2, 2, 2, 2, 2]
print(l.shuffled())  # Never ends.
```

**Comment by qexat** [comment]
Oh right, what a silly mistake :sob: Thank you for the issue!

**Comment by qexat** [comment]
2.4.0, which this commit is in, was just pushed to the PyPI :smile:
